[workspace]
members = [
  "programs/payout_plan"
]

[programs.localnet]
payout_plan = "payoUT1111111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
